include_guard(GLOBAL)
set(_GPLATFORM_BUILD_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

# Shared by the source project and the exported App. Standard tool overrides
# are passed to CMake; each dependency discovers tools when it needs them.
set(_gplatform_qt_help "Set GPLATFORM_QT_ROOT to the platform Qt SDK containing lib/cmake/Qt6/Qt6Config.cmake. Restart the IDE after changing its environment. See README.md for command-line/CI setup.")
if(DEFINED ENV{GPLATFORM_QT_ROOT})
    if("$ENV{GPLATFORM_QT_ROOT}" STREQUAL "")
        message(FATAL_ERROR "GPLATFORM_QT_ROOT is empty. Set the environment variable. ${_gplatform_qt_help}")
    endif()
    file(REAL_PATH "$ENV{GPLATFORM_QT_ROOT}" _environment_qt_root)
    if(GPLATFORM_QT_ROOT)
        file(REAL_PATH "${GPLATFORM_QT_ROOT}" _configured_qt_root)
        if(CMAKE_HOST_WIN32)
            string(TOLOWER "${_environment_qt_root}" _environment_qt_root)
            string(TOLOWER "${_configured_qt_root}" _configured_qt_root)
        endif()
        if(NOT _environment_qt_root STREQUAL _configured_qt_root)
            message(FATAL_ERROR "GPLATFORM_QT_ROOT environment variable ('$ENV{GPLATFORM_QT_ROOT}') conflicts with the configured value ('${GPLATFORM_QT_ROOT}'). Use a separate build directory when changing Qt. ${_gplatform_qt_help}")
        endif()
    endif()
endif()
foreach(_input GPLATFORM_QT_ROOT GPLATFORM_TARGET_ARCH CMAKE_TOOLCHAIN_FILE
        CMAKE_C_COMPILER CMAKE_CXX_COMPILER CMAKE_MAKE_PROGRAM
        Python3_EXECUTABLE GIT_EXECUTABLE PERL_EXECUTABLE)
    if(NOT DEFINED ${_input} AND DEFINED ENV{${_input}} AND NOT "$ENV{${_input}}" STREQUAL "")
        set(${_input} "$ENV{${_input}}" CACHE STRING "Build input: ${_input}")
    endif()
endforeach()
if(NOT GPLATFORM_QT_ROOT)
    message(FATAL_ERROR "GPLATFORM_QT_ROOT is missing. Set the environment variable. ${_gplatform_qt_help}")
endif()
file(TO_CMAKE_PATH "${GPLATFORM_QT_ROOT}" GPLATFORM_QT_ROOT)
cmake_path(ABSOLUTE_PATH GPLATFORM_QT_ROOT NORMALIZE)
set(_qt_package "${GPLATFORM_QT_ROOT}/lib/cmake/Qt6")
if(NOT EXISTS "${_qt_package}/Qt6Config.cmake")
    message(FATAL_ERROR "GPLATFORM_QT_ROOT='${GPLATFORM_QT_ROOT}' has no lib/cmake/Qt6/Qt6Config.cmake. ${_gplatform_qt_help}")
endif()
if(Qt6_DIR AND NOT Qt6_DIR MATCHES "-NOTFOUND$")
    file(REAL_PATH "${Qt6_DIR}" _existing_qt)
    file(REAL_PATH "${_qt_package}" _requested_qt)
    if(NOT _existing_qt STREQUAL _requested_qt)
        message(FATAL_ERROR "Qt6_DIR='${Qt6_DIR}' conflicts with GPLATFORM_QT_ROOT='${GPLATFORM_QT_ROOT}'. Use a separate build directory when changing Qt. ${_gplatform_qt_help}")
    endif()
endif()
set(Qt6_DIR "${_qt_package}" CACHE PATH "Selected Qt package" FORCE)
list(PREPEND CMAKE_PREFIX_PATH "${GPLATFORM_QT_ROOT}")

if(GPLATFORM_TARGET_ARCH AND CMAKE_HOST_APPLE)
    string(REGEX REPLACE "^x64$" "x86_64" _requested_arch "${GPLATFORM_TARGET_ARCH}")
    if(CMAKE_OSX_ARCHITECTURES AND NOT CMAKE_OSX_ARCHITECTURES STREQUAL _requested_arch)
        message(FATAL_ERROR "GPLATFORM_TARGET_ARCH conflicts with CMAKE_OSX_ARCHITECTURES.")
    endif()
    set(CMAKE_OSX_ARCHITECTURES "${_requested_arch}" CACHE STRING "Target architecture")
endif()
# Call after project(). Compiler identification is authoritative; VsDevCmd
# variables and the Visual Studio installation directory are not prerequisites.
macro(gplatform_configure_toolchain)
    if(WIN32 AND NOT MSVC)
        message(FATAL_ERROR "Windows builds require MSVC and a matching Qt SDK. Use scripts/build.cmd or an MSVC developer environment.")
    endif()
    set(_compiler_arch "${CMAKE_SYSTEM_PROCESSOR}")
    if(MSVC)
        set(_compiler_arch "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
    elseif(APPLE AND CMAKE_OSX_ARCHITECTURES)
        set(_compiler_arch "${CMAKE_OSX_ARCHITECTURES}")
    endif()
    if(GPLATFORM_TARGET_ARCH)
        string(TOLOWER "${_compiler_arch}" _actual_arch)
        string(TOLOWER "${GPLATFORM_TARGET_ARCH}" _requested_arch)
        string(REGEX REPLACE "^(amd64|x86_64)$" "x64" _actual_arch "${_actual_arch}")
        string(REGEX REPLACE "^(amd64|x86_64)$" "x64" _requested_arch "${_requested_arch}")
        if(NOT _actual_arch STREQUAL _requested_arch)
            message(FATAL_ERROR "GPLATFORM_TARGET_ARCH=${GPLATFORM_TARGET_ARCH} does not match compiler target ${_compiler_arch}. Use a matching compiler and a separate build directory.")
        endif()
    endif()
    include("${_GPLATFORM_BUILD_CMAKE_DIR}/GPlatformMsvcDependencies.cmake")
endmacro()
