include_guard(GLOBAL)
if(NOT CMAKE_BUILD_TYPE OR CMAKE_CONFIGURATION_TYPES)
    message(FATAL_ERROR "Select one SDK configuration with -DCMAKE_BUILD_TYPE=Release or Debug")
endif()
set(_sdk_arch "${CMAKE_SYSTEM_PROCESSOR}")
if(CMAKE_OSX_ARCHITECTURES)
    set(_sdk_arch "${CMAKE_OSX_ARCHITECTURES}")
endif()
set(GPLATFORM_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../ThirdParty/libs/GPlatformSDK" CACHE PATH "SDK submodule checkout")
set(_sdk_slot "${GPLATFORM_SDK_ROOT}/${_sdk_arch}/${CMAKE_BUILD_TYPE}")
if(NOT EXISTS "${_sdk_slot}/sdk-build.json")
    message(FATAL_ERROR "SDK is missing: ${_sdk_slot}. Run git submodule update --init --recursive and select a published build configuration.")
endif()
file(GLOB_RECURSE _sdk_archives "${_sdk_slot}/lib/*.a" "${_sdk_slot}/lib/*.lib")
foreach(_archive IN LISTS _sdk_archives)
    file(STRINGS "${_archive}" _first_line LIMIT_COUNT 1 LIMIT_INPUT 100)
    if(_first_line MATCHES "^version https://git-lfs.github.com/spec/")
        message(FATAL_ERROR "SDK contains Git LFS pointers. Install Git LFS and run git lfs pull inside ${GPLATFORM_SDK_ROOT}.")
    endif()
endforeach()
file(READ "${_sdk_slot}/sdk-build.json" _sdk_info)
string(JSON _sdk_system GET "${_sdk_info}" CMAKE_SYSTEM_NAME)
if(NOT _sdk_system STREQUAL CMAKE_SYSTEM_NAME)
    message(FATAL_ERROR "This SDK was built for ${_sdk_system}; consumer uses ${CMAKE_SYSTEM_NAME}")
endif()
find_package(GPlatformSDK CONFIG REQUIRED PATHS "${_sdk_slot}/lib/cmake/GPlatformSDK" NO_DEFAULT_PATH)

function(gplatform_deploy_sdk_runtime target)
    if(APPLE)
        set(destination "$<TARGET_FILE_DIR:${target}>/../Frameworks")
        set_property(TARGET ${target} APPEND PROPERTY BUILD_RPATH "@executable_path/../Frameworks")
        file(GLOB runtime CONFIGURE_DEPENDS "${_sdk_slot}/lib/*.dylib")
    elseif(WIN32)
        set(destination "$<TARGET_FILE_DIR:${target}>")
        file(GLOB runtime CONFIGURE_DEPENDS "${_sdk_slot}/lib/*.dll")
    else()
        set(destination "$<TARGET_FILE_DIR:${target}>")
        file(GLOB runtime CONFIGURE_DEPENDS "${_sdk_slot}/lib/*.so*")
    endif()
    if(runtime)
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${destination}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${runtime} "${destination}"
            COMMAND_EXPAND_LISTS VERBATIM)
    endif()
endfunction()
