include_guard(GLOBAL)
if(NOT CMAKE_BUILD_TYPE OR CMAKE_CONFIGURATION_TYPES)
    message(FATAL_ERROR "Select one SDK configuration with -DCMAKE_BUILD_TYPE=Release or Debug")
endif()
set(_sdk_arch "${CMAKE_SYSTEM_PROCESSOR}")
if(MSVC)
    string(REGEX REPLACE "^x64$" "AMD64" _sdk_arch "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
elseif(CMAKE_OSX_ARCHITECTURES)
    set(_sdk_arch "${CMAKE_OSX_ARCHITECTURES}")
endif()
if(NOT DEFINED GPLATFORM_SDK_ROOT)
    set(GPLATFORM_SDK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../ThirdParty/libs/GPlatformSDK" CACHE PATH "SDK submodule checkout")
endif()
set(_sdk_slot "${GPLATFORM_SDK_ROOT}/${_sdk_arch}/${CMAKE_BUILD_TYPE}")
if(NOT EXISTS "${_sdk_slot}/sdk-build.json")
    file(GLOB _available_sdk_builds RELATIVE "${GPLATFORM_SDK_ROOT}" "${GPLATFORM_SDK_ROOT}/*/*/sdk-build.json")
    if(NOT _available_sdk_builds AND NOT EXISTS "${GPLATFORM_SDK_ROOT}/.git")
        message(FATAL_ERROR "SDK checkout is missing or its submodule is not initialized: ${GPLATFORM_SDK_ROOT}. Run git submodule update --init --recursive, then git -C ${GPLATFORM_SDK_ROOT} lfs pull.")
    endif()
    message(FATAL_ERROR "The selected SDK version has no ${CMAKE_SYSTEM_NAME}/${_sdk_arch}/${CMAKE_BUILD_TYPE} package at ${_sdk_slot}. Available builds: ${_available_sdk_builds}. Publish a matching SDK and update the App submodule pointer, or select an available configuration.")
endif()
# Check files used by configure and link, including runtime DLLs. LFS metadata
# and CMake packages must be materialized before parsing them.
file(GLOB_RECURSE _sdk_files "${_sdk_slot}/lib/*.a" "${_sdk_slot}/lib/*.lib"
    "${_sdk_slot}/lib/*.o" "${_sdk_slot}/lib/*.obj"
    "${_sdk_slot}/objects/*.o" "${_sdk_slot}/objects/*.obj"
    "${_sdk_slot}/lib/*.cmake" "${_sdk_slot}/lib/*.dll" "${_sdk_slot}/bin/*.dll"
    "${_sdk_slot}/lib/*.dylib" "${_sdk_slot}/lib/*.so*")
list(APPEND _sdk_files "${_sdk_slot}/sdk-build.json")
foreach(_sdk_file IN LISTS _sdk_files)
    file(READ "${_sdk_file}" _first_line LIMIT 100)
    if(_first_line MATCHES "^version https://git-lfs.github.com/spec/")
        message(FATAL_ERROR "SDK contains Git LFS pointers. Install Git LFS and run git lfs pull inside ${GPLATFORM_SDK_ROOT}.")
    endif()
endforeach()
file(READ "${_sdk_slot}/sdk-build.json" _sdk_info)
string(JSON _sdk_system GET "${_sdk_info}" CMAKE_SYSTEM_NAME)
if(NOT _sdk_system STREQUAL CMAKE_SYSTEM_NAME)
    message(FATAL_ERROR "This SDK was built for ${_sdk_system}; consumer uses ${CMAKE_SYSTEM_NAME}")
endif()
string(JSON _sdk_compiler GET "${_sdk_info}" CMAKE_CXX_COMPILER_ID)
if(NOT _sdk_compiler STREQUAL CMAKE_CXX_COMPILER_ID)
    message(FATAL_ERROR "This SDK requires ${_sdk_compiler}; consumer compiler is ${CMAKE_CXX_COMPILER_ID}. Select a compatible compiler or publish a matching SDK.")
endif()
set(GPlatformSDK_DIR "${_sdk_slot}/lib/cmake/GPlatformSDK" CACHE PATH "Selected SDK package" FORCE)
find_package(GPlatformSDK CONFIG REQUIRED PATHS "${_sdk_slot}/lib/cmake/GPlatformSDK" NO_DEFAULT_PATH)

function(gplatform_deploy_sdk_runtime target)
    if(APPLE)
        set(destination "$<TARGET_FILE_DIR:${target}>/../Frameworks")
        set_property(TARGET ${target} APPEND PROPERTY BUILD_RPATH "@executable_path/../Frameworks")
        file(GLOB runtime CONFIGURE_DEPENDS "${_sdk_slot}/lib/*.dylib")
    elseif(WIN32)
        set(destination "$<TARGET_FILE_DIR:${target}>")
        file(GLOB runtime CONFIGURE_DEPENDS "${_sdk_slot}/lib/*.dll")
    else()
        set(destination "$<TARGET_FILE_DIR:${target}>")
        file(GLOB runtime CONFIGURE_DEPENDS "${_sdk_slot}/lib/*.so*")
    endif()
    if(runtime)
        set(stamp "${CMAKE_CURRENT_BINARY_DIR}/${target}-sdk-runtime.stamp")
        add_custom_command(OUTPUT "${stamp}"
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${destination}"
            COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${runtime} "${destination}"
            COMMAND "${CMAKE_COMMAND}" -E touch "${stamp}"
            DEPENDS ${runtime} "${_sdk_slot}/sdk-manifest.json"
            COMMAND_EXPAND_LISTS VERBATIM)
        add_custom_target(${target}_sdk_runtime DEPENDS "${stamp}")
        add_dependencies(${target} ${target}_sdk_runtime)
    endif()
endfunction()
